[window]
blur = true
opacity = 0.8
decorations = "Buttonless"
padding = { x = 20, y = 20 }
option_as_alt = "Both"

[font]
normal = { family = "TerminessTTF Nerd Font Mono" }
size = 16

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "v", mods = "Option", action = "ToggleViMode" },
    { key = "q", mode = "Vi", action = "ToggleViMode" }
]

[debug]
log_level = "Off"
